:Author: screamingeaglecz
:Email: {AuthorEmail}
:Date: 05/03/2020
:Revision: version#
:License: Public Domain

= Project: {Project}

Initial Setup of HC-06 module by AT commands


== Step 1: Installation
Please describe the steps to install this project.

For example:

Different versions of HC modules exists and there is also different AT commands for them...(commands for HC-06 v 3.0)
Write in serial monitor AT+VERSION to get version from module
                        AT - should return OK from HC module
                        AT+NAME:DesiredName - Change name
                        AT+UART=115200,0,0 - Change speed to 115200:
                        AT+PSWD:"0000" - Change pin:



== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact screamingeaglecz https://id.arduino.cc/screamingeaglecz

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
